/* eslint-disable import/no-anonymous-default-export */
enum ACTIONS {
    STARTING_COUNTRY_REQUESTING,
    STARTING_COUNTRY_FAILED,
    STARTING_COUNTRY_SUCCESS,

    DESTINATION_COUNTRY_REQUESTING,
    DESTINATION_COUNTRY_FAILED,
    DESTINATION_COUNTRY_SUCCESS,

    PICKUP_LOCATION_REQUESTING,
    PICKUP_LOCATION_FAILED,
    PICKUP_LOCATION_SUCCESS,

    QUOTE_REQUESTING,
    QUOTE_FAILED,
    QUOTE_SUCCESS,
}

export default ACTIONS